kind: pipeline
name: default

steps:
- name: message
  image: ubuntu
  commands:
  - echo "hello world"
  - apt-get update
  - pwd
  - ls -ltra
  - cp test test1
  - export papa=john

- name: message2
  image: ubuntu
  commands:
  - echo "hello world"
  - apt-get update
  - pwd
  - ls -ltra
  - cp test1 test2
  - printenv | grep papa

