kind: pipeline
name: default

steps:
- name: test
  image: vault:1.0.0-beta2
  environment:
    VAULT_ADDR: http://vault:8200
    VAULT_TOKEN: dummy
  commands:
  - sleep 5
  - vault kv put secret/my-secret my-value=s3cr3t
  - vault kv get secret/my-secret

services:
- name: vault
  image: vault:1.0.0-beta2
  environment:
    VAULT_DEV_ROOT_TOKEN_ID: dummy
  ports:
  - 8200
