kind: pipeline
name: default

steps:
- name: message
  image: ubuntu
  commands:
  - echo "hello world"
  - curl -X POST --data '{"text":"hello","channel":"#general"}' https://hooks.slack.com/services/...
